### ISSUE TITLE
Swagger url and swagger-dropwizard integration

### ISSUE THREAD

**Issue by mastermind1981** [Trunkplatform/lazybones-dropwizard-turbo#2]
Hi,

Could you please provide the url used by swagger ?

Is it possible to integrate the swagger dropwizard bundle instead of the current implementation?

Thanks in advance,

**Comment by mrserverless** [comment]
The url used by swagger can be found in the logs when your service starts up:

```
GET     /api-docs (com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON)
GET     /api-docs/{route: .+} (com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON)
```

You can run swagger-ui separately and point to those urls to see your API.

I didn't want to include the swagger bundle because it has `swagger-ui` built in. I think it's unnecessary for every API / Microservice to be carrying their own `swagger-ui`, which in turn requires `asset-bundle` and extra configurations. Each of your DW service should be responsible for their specific domain, and swagger-ui should be served by a separate dedicated service pointing to each api-doc url

**Comment by mastermind1981** [comment]
thank you

**Comment by mrserverless** [comment]
Closing this. Let me know if you have any issues. I'll be creating a separate bundle/module for the lightweight swagger integration I'm using. Will keep you posted.
